export const eventData = [
  {
    image: "../img/Image.svg",
    eventId: "GHJ567D",
    location: "Casablanca",
    price: 199,
    category: "Music",
    title: "Casablanca Music Festival",
    date: "2023-07-15T18:30:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "JKL234S",
    location: "Marrakech",
    price: 599,
    category: "Art | Culture",
    title: "Marrakech Art Exhibition",
    date: "2023-08-05T15:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "TGB789F",
    location: "Tangier",
    price: 49,
    category: "Food | Drink",
    title: "Tangier Food Tasting",
    date: "2023-06-22T19:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "FRT345H",
    location: "Fez",
    price: 149,
    category: "Theater | Cinema",
    title: "Fez Film Festival",
    date: "2023-09-01T17:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "CVB123A",
    location: "Agadir",
    price: 249,
    category: "Sport",
    title: "Agadir Surfing Competition",
    date: "2023-07-12T10:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "QWE987P",
    location: "Ouarzazate",
    price: 79,
    category: "Art | Culture",
    title: "Ouarzazate Photography Exhibition",
    date: "2023-08-17T14:30:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "VBN234G",
    location: "Essaouira",
    price: 299,
    category: "Music",
    title: "Essaouira Jazz Festival",
    date: "2023-09-10T20:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "TYU345J",
    location: "Meknes",
    price: 39,
    category: "Food | Drink",
    title: "Meknes Street Food Festival",
    date: "2023-07-08T18:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "MNB123X",
    location: "Tetouan",
    price: 99,
    category: "Sport",
    title: "Tetouan Marathon",
    date: "2023-05-20T07:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "PLK876G",
    location: "Chefchaouen",
    price: 149,
    category: "Art | Culture",
    title: "Chefchaouen Street Art Festival",
    date: "2023-06-30T12:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "QAZ675B",
    location: "Rabat",
    price: 199,
    category: "Sport",
    title: "Tangier Marathon",
    date: "2022-11-05T09:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "WENCMFI",
    location: "Marrakech",
    price: 149,
    category: "Art | Culture",
    title: "Marrakech Art & Culture Festival",
    date: "2023-03-18T19:30:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "KDJYRNX",
    location: "Casablanca",
    price: 199,
    category: "Music",
    title: "Jazz Night at Casablanca Palace",
    date: "2023-04-02T20:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "JCYXJLW",
    location: "Fez",
    price: 89,
    category: "Food | Drink",
    title: "Fez Food & Wine Festival",
    date: "2023-05-12T18:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "EUROXKF",
    location: "Tangier",
    price: 129,
    category: "Sport",
    title: "Tangier International Marathon",
    date: "2023-06-04T07:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "JCYZCNV",
    location: "Agadir",
    price: 79,
    category: "Nature",
    title: "Agadir Eco-Tour",
    date: "2023-07-15T09:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "DKEIPAM",
    location: "Rabat",
    price: 139,
    category: "Theater | Cinema",
    title: "Rabat Film Festival",
    date: "2023-08-06T21:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "CJYDHFR",
    location: "Essaouira",
    price: 199,
    category: "Music",
    title: "Essaouira World Music Festival",
    date: "2023-09-08T20:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "EKDHZMN",
    location: "Fquih Ben Salah",
    price: 49,
    category: "Art | Culture",
    title: "Art in the Atlas Mountains",
    date: "2023-10-14T10:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "CYDIXJV",
    location: "Ouarzazate",
    price: 149,
    category: "Theater | Cinema",
    title: "Ouarzazate Film Festival",
    date: "2023-11-20T19:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "EJYDNZX",
    location: "Tétouan",
    price: 99,
    category: "Sport",
    title: "Tétouan Cycling Tour",
    date: "2023-12-09T08:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "JCYFMYR",
    location: "Agadir",
    price: 149,
    category: "Food | Drink",
    title: "Agadir Seafood Festival",
    date: "2023-03-25T19:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "ECJDKWV",
    location: "Agadir",
    price: 99,
    category: "Sport",
    title: "Agadir Surf Competition",
    date: "2023-04-16T08:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "JCYFWCN",
    location: "Agadir",
    price: 79,
    category: "Nature",
    title: "Agadir Desert Trek",
    date: "2023-05-20T06:00:00",
  },
  {
    image: "../img/Image.svg",
    eventId: "KDJCYOR",
    location: "Agadir",
    price: 129,
    category: "Art | Culture",
    title: "Agadir Street Art Festival",
    date: "2023-06-17T16:00:00",
  },
];
export const account = [
  {
    Username: "Jada Mohamed",
    City: "Agadir",
  },
];
